using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InspectionApi.Migrations
{
    /// <inheritdoc />
    public partial class DataSafetyModelSync : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                ALTER TABLE ""Properties""
                ADD COLUMN IF NOT EXISTS ""PropertyCondition"" text NULL;

                ALTER TABLE ""InspectionRecords""
                ADD COLUMN IF NOT EXISTS ""ParkingFee"" numeric NULL;

                CREATE TABLE IF NOT EXISTS ""TaskTypes"" (
                    ""Id""           integer               NOT NULL,
                    ""Name""         character varying(50) NOT NULL,
                    ""Color""        character varying(30) NOT NULL DEFAULT 'default',
                    ""DisplayOrder"" integer               NOT NULL DEFAULT 0,
                    CONSTRAINT ""PK_TaskTypes"" PRIMARY KEY (""Id"")
                );
                INSERT INTO ""TaskTypes"" (""Id"", ""Name"", ""Color"", ""DisplayOrder"") VALUES
                    (0, 'Move In',  'cyan',    0),
                    (1, 'Move Out', 'gold',    1),
                    (2, 'Routine',  'green',   2),
                    (3, 'Other',    'default', 3)
                ON CONFLICT (""Id"") DO NOTHING;
                CREATE INDEX IF NOT EXISTS ""IX_TaskTypes_DisplayOrder""
                    ON ""TaskTypes"" (""DisplayOrder"");

                CREATE TABLE IF NOT EXISTS ""TemplateInspectionTypes"" (
                    ""Id""           integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name""         character varying(50) NOT NULL,
                    ""DisplayOrder"" integer               NOT NULL DEFAULT 0,
                    CONSTRAINT ""PK_TemplateInspectionTypes"" PRIMARY KEY (""Id"")
                );
                CREATE INDEX IF NOT EXISTS ""IX_TemplateInspectionTypes_DisplayOrder""
                    ON ""TemplateInspectionTypes"" (""DisplayOrder"");

                CREATE TABLE IF NOT EXISTS ""GeneralTemplates"" (
                    ""Id""               integer GENERATED BY DEFAULT AS IDENTITY,
                    ""InspectionTypeId"" integer                 NOT NULL,
                    ""Text""             character varying(2000) NOT NULL DEFAULT '',
                    CONSTRAINT ""PK_GeneralTemplates"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_GeneralTemplates_TemplateInspectionTypes_InspectionTypeId""
                        FOREIGN KEY (""InspectionTypeId"")
                        REFERENCES ""TemplateInspectionTypes"" (""Id"") ON DELETE CASCADE
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_GeneralTemplates_InspectionTypeId""
                    ON ""GeneralTemplates"" (""InspectionTypeId"");

                CREATE TABLE IF NOT EXISTS ""TenantContacts"" (
                    ""Id""            integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PropertyId""    integer                 NOT NULL,
                    ""SourceAddress"" character varying(200)  NOT NULL,
                    ""Phone""         character varying(80)   NOT NULL DEFAULT '',
                    ""Email""         character varying(500)  NOT NULL DEFAULT '',
                    ""LeaseDateEnded"" character varying(50)   NOT NULL DEFAULT '',
                    ""ImportedAt""    timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_TenantContacts"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_TenantContacts_Properties_PropertyId""
                        FOREIGN KEY (""PropertyId"") REFERENCES ""Properties"" (""Id"") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_TenantContacts_PropertyId""
                    ON ""TenantContacts"" (""PropertyId"");
                CREATE INDEX IF NOT EXISTS ""IX_TenantContacts_SourceAddress""
                    ON ""TenantContacts"" (""SourceAddress"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS ""GeneralTemplates"";
                DROP TABLE IF EXISTS ""TaskTypes"";
                DROP TABLE IF EXISTS ""TenantContacts"";
                DROP TABLE IF EXISTS ""TemplateInspectionTypes"";

                ALTER TABLE ""Properties""
                DROP COLUMN IF EXISTS ""PropertyCondition"";

                ALTER TABLE ""InspectionRecords""
                DROP COLUMN IF EXISTS ""ParkingFee"";
            ");
        }
    }
}
