namespace InspectionApi.Data
{
    public static class DatabaseStartupSql
    {
        public const string SystemSettingsTableSql = @"
                CREATE TABLE IF NOT EXISTS ""SystemSettings"" (
                    ""Key""   character varying(100) NOT NULL,
                    ""Value"" text                   NOT NULL DEFAULT '',
                    CONSTRAINT ""PK_SystemSettings"" PRIMARY KEY (""Key"")
                );
                INSERT INTO ""SystemSettings"" (""Key"", ""Value"")
                VALUES ('AiInspectionReportPrompt', '')
                ON CONFLICT (""Key"") DO NOTHING;
            ";

        public const string PropertiesTableSql = @"
                ALTER TABLE ""Properties""
                ADD COLUMN IF NOT EXISTS ""PropertyCondition"" text NULL;
            ";

        public const string InspectionTasksTableSql = @"
                ALTER TABLE ""InspectionTasks""
                ALTER COLUMN ""Notes"" TYPE text;
            ";

        public const string InspectionRecordsTableSql = @"
                DO $$
                DECLARE
                    work_units_exists boolean;
                BEGIN
                    SELECT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public'
                          AND table_name = 'InspectionRecords'
                          AND column_name = 'WorkUnits'
                    ) INTO work_units_exists;

                    IF NOT work_units_exists THEN
                        ALTER TABLE ""InspectionRecords""
                        ADD COLUMN ""WorkUnits"" integer NULL;

                        UPDATE ""InspectionRecords""
                        SET ""WorkUnits"" = CASE
                            WHEN ""Type"" IN (0, 1) THEN 2
                            ELSE 1
                        END;
                    ELSE
                        UPDATE ""InspectionRecords""
                        SET ""WorkUnits"" = CASE
                            WHEN ""Type"" IN (0, 1) THEN 2
                            ELSE 1
                        END
                        WHERE ""WorkUnits"" IS NULL OR ""WorkUnits"" NOT IN (1, 2);
                    END IF;

                    ALTER TABLE ""InspectionRecords""
                    ALTER COLUMN ""WorkUnits"" SET DEFAULT 1;

                    ALTER TABLE ""InspectionRecords""
                    ALTER COLUMN ""WorkUnits"" SET NOT NULL;
                END $$;
            ";

        public const string WorkflowsTableSql = @"
                CREATE TABLE IF NOT EXISTS ""Workflows"" (
                    ""Id""                  integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Type""                integer                 NOT NULL DEFAULT 0,
                    ""Address""             character varying(200)  NOT NULL,
                    ""AddressKey""          character varying(200)  NOT NULL,
                    ""Stage""               integer                 NOT NULL DEFAULT 0,
                    ""MoveInAppointmentAt"" timestamp with time zone NULL,
                    ""Notes""               text                    NULL,
                    ""IsArchived""          boolean                 NOT NULL DEFAULT false,
                    ""CreatedAt""           timestamp with time zone NOT NULL DEFAULT now(),
                    ""UpdatedAt""           timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_Workflows"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""WorkflowChecklistItems"" (
                    ""Id""           integer GENERATED BY DEFAULT AS IDENTITY,
                    ""WorkflowId""   integer                NOT NULL,
                    ""Key""          character varying(80)  NOT NULL,
                    ""Label""        character varying(200) NOT NULL,
                    ""Stage""        integer                NOT NULL,
                    ""DisplayOrder"" integer                NOT NULL,
                    ""IsCompleted""  boolean                NOT NULL DEFAULT false,
                    ""CompletedAt""  timestamp with time zone NULL,
                    CONSTRAINT ""PK_WorkflowChecklistItems"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_WorkflowChecklistItems_Workflows_WorkflowId""
                        FOREIGN KEY (""WorkflowId"") REFERENCES ""Workflows"" (""Id"") ON DELETE CASCADE
                );

                DROP INDEX IF EXISTS ""IX_Workflows_Type_AddressKey_IsArchived"";
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Workflows_Type_AddressKey_Active""
                    ON ""Workflows"" (""Type"", ""AddressKey"") WHERE ""IsArchived"" = false;
                CREATE INDEX IF NOT EXISTS ""IX_Workflows_Stage"" ON ""Workflows"" (""Stage"");
                CREATE INDEX IF NOT EXISTS ""IX_Workflows_MoveInAppointmentAt"" ON ""Workflows"" (""MoveInAppointmentAt"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_WorkflowChecklistItems_WorkflowId_Key""
                    ON ""WorkflowChecklistItems"" (""WorkflowId"", ""Key"");
                CREATE INDEX IF NOT EXISTS ""IX_WorkflowChecklistItems_WorkflowId_DisplayOrder""
                    ON ""WorkflowChecklistItems"" (""WorkflowId"", ""DisplayOrder"");
            ";

        public const string IdentitySequenceSyncSql = @"
                DO $$
                DECLARE
                    seq  text;
                    nval bigint;
                BEGIN
                    -- Properties
                    seq := pg_get_serial_sequence('""Properties""', 'Id');
                    IF seq IS NOT NULL THEN
                        SELECT COALESCE(MAX(""Id""), 0) + 1 INTO nval FROM ""Properties"";
                        PERFORM setval(seq, nval, false);
                    END IF;

                    -- InspectionRecords
                    seq := pg_get_serial_sequence('""InspectionRecords""', 'Id');
                    IF seq IS NOT NULL THEN
                        SELECT COALESCE(MAX(""Id""), 0) + 1 INTO nval FROM ""InspectionRecords"";
                        PERFORM setval(seq, nval, false);
                    END IF;

                    -- TenantContacts
                    seq := pg_get_serial_sequence('""TenantContacts""', 'Id');
                    IF seq IS NOT NULL THEN
                        SELECT COALESCE(MAX(""Id""), 0) + 1 INTO nval FROM ""TenantContacts"";
                        PERFORM setval(seq, nval, false);
                    END IF;

                    -- InspectionTasks
                    seq := pg_get_serial_sequence('""InspectionTasks""', 'Id');
                    IF seq IS NOT NULL THEN
                        SELECT COALESCE(MAX(""Id""), 0) + 1 INTO nval FROM ""InspectionTasks"";
                        PERFORM setval(seq, nval, false);
                    END IF;

                    -- TemplateInspectionTypes
                    seq := pg_get_serial_sequence('""TemplateInspectionTypes""', 'Id');
                    IF seq IS NOT NULL THEN
                        SELECT COALESCE(MAX(""Id""), 0) + 1 INTO nval FROM ""TemplateInspectionTypes"";
                        PERFORM setval(seq, nval, false);
                    END IF;

                    -- GeneralTemplates
                    seq := pg_get_serial_sequence('""GeneralTemplates""', 'Id');
                    IF seq IS NOT NULL THEN
                        SELECT COALESCE(MAX(""Id""), 0) + 1 INTO nval FROM ""GeneralTemplates"";
                        PERFORM setval(seq, nval, false);
                    END IF;

                    -- Workflows
                    seq := pg_get_serial_sequence('""Workflows""', 'Id');
                    IF seq IS NOT NULL THEN
                        SELECT COALESCE(MAX(""Id""), 0) + 1 INTO nval FROM ""Workflows"";
                        PERFORM setval(seq, nval, false);
                    END IF;

                    -- WorkflowChecklistItems
                    seq := pg_get_serial_sequence('""WorkflowChecklistItems""', 'Id');
                    IF seq IS NOT NULL THEN
                        SELECT COALESCE(MAX(""Id""), 0) + 1 INTO nval FROM ""WorkflowChecklistItems"";
                        PERFORM setval(seq, nval, false);
                    END IF;
                END $$;
            ";

        public const string TenantContactsTableSql = @"
                CREATE TABLE IF NOT EXISTS ""TenantContacts"" (
                    ""Id""            integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PropertyId""    integer                 NOT NULL,
                    ""SourceAddress"" character varying(200)  NOT NULL,
                    ""Phone""         character varying(80)   NOT NULL DEFAULT '',
                    ""Email""         character varying(500)  NOT NULL DEFAULT '',
                    ""LeaseDateEnded"" character varying(50)   NOT NULL DEFAULT '',
                    ""ImportedAt""    timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_TenantContacts"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_TenantContacts_Properties_PropertyId""
                        FOREIGN KEY (""PropertyId"") REFERENCES ""Properties"" (""Id"") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_TenantContacts_PropertyId"" ON ""TenantContacts"" (""PropertyId"");
                CREATE INDEX IF NOT EXISTS ""IX_TenantContacts_SourceAddress"" ON ""TenantContacts"" (""SourceAddress"");
                ALTER TABLE ""TenantContacts""
                ADD COLUMN IF NOT EXISTS ""LeaseDateEnded"" character varying(50) NOT NULL DEFAULT '';
            ";
    }
}
