namespace InspectionApi.Data
{
    public static class DatabaseStartupSql
    {
        public const string PropertiesTableSql = @"
                ALTER TABLE ""Properties""
                ADD COLUMN IF NOT EXISTS ""PropertyCondition"" text NULL;
            ";

        public const string InspectionTasksTableSql = @"
                ALTER TABLE ""InspectionTasks""
                ALTER COLUMN ""Notes"" TYPE text;
            ";

        public const string IdentitySequenceSyncSql = @"
                DO $$
                DECLARE
                    seq  text;
                    nval bigint;
                BEGIN
                    -- Properties
                    seq := pg_get_serial_sequence('""Properties""', 'Id');
                    IF seq IS NOT NULL THEN
                        SELECT COALESCE(MAX(""Id""), 0) + 1 INTO nval FROM ""Properties"";
                        PERFORM setval(seq, nval, false);
                    END IF;

                    -- InspectionRecords
                    seq := pg_get_serial_sequence('""InspectionRecords""', 'Id');
                    IF seq IS NOT NULL THEN
                        SELECT COALESCE(MAX(""Id""), 0) + 1 INTO nval FROM ""InspectionRecords"";
                        PERFORM setval(seq, nval, false);
                    END IF;

                    -- TenantContacts
                    seq := pg_get_serial_sequence('""TenantContacts""', 'Id');
                    IF seq IS NOT NULL THEN
                        SELECT COALESCE(MAX(""Id""), 0) + 1 INTO nval FROM ""TenantContacts"";
                        PERFORM setval(seq, nval, false);
                    END IF;

                    -- InspectionTasks
                    seq := pg_get_serial_sequence('""InspectionTasks""', 'Id');
                    IF seq IS NOT NULL THEN
                        SELECT COALESCE(MAX(""Id""), 0) + 1 INTO nval FROM ""InspectionTasks"";
                        PERFORM setval(seq, nval, false);
                    END IF;

                    -- TemplateInspectionTypes
                    seq := pg_get_serial_sequence('""TemplateInspectionTypes""', 'Id');
                    IF seq IS NOT NULL THEN
                        SELECT COALESCE(MAX(""Id""), 0) + 1 INTO nval FROM ""TemplateInspectionTypes"";
                        PERFORM setval(seq, nval, false);
                    END IF;

                    -- GeneralTemplates
                    seq := pg_get_serial_sequence('""GeneralTemplates""', 'Id');
                    IF seq IS NOT NULL THEN
                        SELECT COALESCE(MAX(""Id""), 0) + 1 INTO nval FROM ""GeneralTemplates"";
                        PERFORM setval(seq, nval, false);
                    END IF;
                END $$;
            ";

        public const string TenantContactsTableSql = @"
                CREATE TABLE IF NOT EXISTS ""TenantContacts"" (
                    ""Id""            integer GENERATED BY DEFAULT AS IDENTITY,
                    ""PropertyId""    integer                 NOT NULL,
                    ""SourceAddress"" character varying(200)  NOT NULL,
                    ""Phone""         character varying(80)   NOT NULL DEFAULT '',
                    ""Email""         character varying(500)  NOT NULL DEFAULT '',
                    ""LeaseDateEnded"" character varying(50)   NOT NULL DEFAULT '',
                    ""ImportedAt""    timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT ""PK_TenantContacts"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_TenantContacts_Properties_PropertyId""
                        FOREIGN KEY (""PropertyId"") REFERENCES ""Properties"" (""Id"") ON DELETE CASCADE
                );
                CREATE INDEX IF NOT EXISTS ""IX_TenantContacts_PropertyId"" ON ""TenantContacts"" (""PropertyId"");
                CREATE INDEX IF NOT EXISTS ""IX_TenantContacts_SourceAddress"" ON ""TenantContacts"" (""SourceAddress"");
                ALTER TABLE ""TenantContacts""
                ADD COLUMN IF NOT EXISTS ""LeaseDateEnded"" character varying(50) NOT NULL DEFAULT '';
            ";
    }
}
